markdown: kramdown

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
plugins: [jekyll-paginate]
# Setup
title:               Mindi Byrum
tagline:             'Portfolio'
description:         'Freelance Editor with a Bachelor's Degree in English, pursuing a career in editing, copywriting, or public relations!'
url:                 https://mindibyrum.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
