markdown: kramdown

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
plugins: [jekyll-paginate]
# Setup
title:               Mindi Byrum
tagline:             'Portfolio'
description:         "Freelance Editor with a Bachelor's Degree in English, pursuing a career in editing, copywriting, or public relations!"
url:                 https://mindibyrum.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mindi Byrum
  url:               www.linkedin.com/in/mindi-byrum
  email:             mindibyrum@gmail.com
  gravatar_md5:      https://s.gravatar.com/avatar/fe4aba15308da8846f535d91c3bdbf5b?s=80

# Custom vars
version:             1.0.0
